@startuml

class Etablissement {

    -nom:string
    -slug:string
    -description:string
    -telephone:string
    -adresse:string
    -ville: Ville
    -email:string
    -image:string
    -actif:bool
    -accueil:bool
    -createdAt :DATETIME
    -updateAt :DATETIME
    -categorie : Categorie[]
}

class Ville {
    -nom : string
    -codePostal : string
    -département :string
    -numeroDepartement : string
    -region :string
}

class Categorie{
    -nom :string
    -createdAt:DATETIME
}

Ville "1..1"-- "0..*" Etablissement
Categorie "1..1"--"0..*" Etablissement


@endum